### ISSUE TITLE
deleting account

### ISSUE THREAD

**Issue by TigerTix** [TigerTix/TigerTix#1]
Once you delete an account, you do not get redirected to the sign in page.

My thought is that it tries to bring you to sign in page but then there is something, like signed in, that brings you to a main but then now there isn't an account then it gets stuck in the loop

**Comment by CamdenSpehl** [comment]
@Devstachio You need to trigger a sign out before account deletion. Not sure of exactly the process in order to do that but thats what you need to do. 

Alternatively, maybe clearing the session cookies could work? That is essentially what sign out is doing, but your problem is that there is session data in the browser still but no user.
